DEBUG = True
ASSETS_DEBUG = True

SECRET_KEY = "ykFhoRTYBZlij522XT5TmB5zJ0kGST"
AWS_ACCESS_KEY_ID = "AKIAJZPW6NNUKGTXEC3A"
AWS_SECRET_ACCESS_KEY = "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"

S3_DOCUMENTS_BUCKET = "dev.easyfoodstamps.documents"
